# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://ngb:nbg123@admin.9c0phnx.mongodb.net/bike_rental_db?retryWrites=true&w=majority&appName=admin
spring.data.mongodb.database=bike_rental_db

# Server
server.port=8080

# JWT Configuration
jwt.secret=dGhpc0lzTXlTZWNyZXRKd3RLZXlGb3JCaWtlUmVudGFsU3lzdGVtMjAyNA==
jwt.expiration=604800000

# Logging
logging.level.org.springframework.security=WARN
logging.level.com.bikerental=DEBUG
logging.level.org.springframework.data.mongodb=WARN
